# Generated by Django 5.0.1 on 2024-01-15 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_content_service_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='image',
            new_name='content',
        ),
    ]
