# Generated by Django 5.0.1 on 2024-01-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_content_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='content',
            field=models.TextField(null=True, verbose_name='Contenido'),
        ),
    ]
