# Generated by Django 5.0.1 on 2024-01-17 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='get_posts', to='blog.category', verbose_name='Categorías'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 23, 35, 47, 874570, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
